### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by BambiGaming2022** [ItsLJcool/YoshiCrafterEngine-LJ-Optimized#1]
Add Extra Keys To make it harder :trollface:

**Comment by SrtHero278** [comment]
Not yet.
We're (or at least me) trying to get the bare essentials for yce-opt.
We'll get to extra features soon.
Sorry.

**Comment by ItsLJcool** [comment]
The engine isnt even completed, TitleState doesnt even exist so until we get a ground basis, no action build (since its useless)

**Comment by BambiGaming2022** [comment]
But i want to download this-

**Comment by SrtHero278** [comment]
We know that. However, this engine is at an **extremely early stage of development.** So early, **_we don't even have stages yet._**
Because of that, we will not add an action build because barebones this repo is.
But to compensate for you wanting a download, here is a [Google Drive folder containing the latest build.](https://drive.google.com/drive/folders/1r46zROezkkzscldR5PFvq0fXdkYrQUEu?usp=sharing)

**Comment by BambiGaming2022** [comment]
Ok thanks, i will wake up and download this
